version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - "8000:8000"
    
    command: bash -c "./setup.bash && python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert/cert.pem --key-file cert/key.pem"
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=https://localhost:8000
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge 