# Generated by Django 4.2.7 on 2024-12-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("file", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="filesharelink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_file_link_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fileshare",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_file",
                to="file.files",
            ),
        ),
        migrations.AddField(
            model_name="fileshare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_file_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="files",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filepermission",
            name="share_file",
            field=models.ForeignKey(
                db_column="file_share_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_file_id",
                to="file.fileshare",
            ),
        ),
        migrations.AddField(
            model_name="filemetadata",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_metadata",
                to="file.files",
            ),
        ),
    ]
